server:
  port: 8083

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: student-service
              uri: lb://STUDENT-SERVICE
              predicates:
                - Path=/students/**
            - id: fees-service
              uri: lb://FEES-COLLECTION-SERVICE
              predicates:
                - Path=/fees/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: api-gateway
    instance-id: ${spring.application.name}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  info:
    env:
      enabled: true
logging:
  pattern:
    level: "%5p [${spring.application.name},correlationId=%X{correlationId:-}]"
info:
  app:
    name: "API Gateway"
    description: "API Gateway"
    version: "1.0.0"
